### ISSUE TITLE
Path: panic: runtime error: while pressing tab as input 

### ISSUE THREAD

**Issue by HemantJoshi11** [JoaoDanielRufino/go-input-autocomplete#18]
Hi,

I have pressed tab once input was asked. go-input-autocomplete was crashed with the following error.

`$ go run cmd/main.go 
Path: panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/JoaoDanielRufino/go-input-autocomplete.autocomplete.unixAutocomplete(0x5115a0, 0x5e1088, 0x0, 0x0, 0x1000000010000, 0x9, 0x0, 0x0)
	/media/sf_gopath/src/go-input-autocomplete/autocomplete.go:35 +0x56c
github.com/JoaoDanielRufino/go-input-autocomplete.Autocomplete(0x0, 0x0, 0x0, 0xc0000942a0, 0xc0000a2ddf, 0x1)
	/media/sf_gopath/src/go-input-autocomplete/autocomplete.go:20 +0x77
github.com/JoaoDanielRufino/go-input-autocomplete.(*Input).Autocomplete(0xc0000a2ee8, 0x0, 0x0)
	/media/sf_gopath/src/go-input-autocomplete/input.go:65 +0x3c
github.com/JoaoDanielRufino/go-input-autocomplete.keyboardListener(0xc0000a2ee8, 0xc0000b4020, 0x0)
	/media/sf_gopath/src/go-input-autocomplete/input_autocomplete.go:28 +0xf1
github.com/JoaoDanielRufino/go-input-autocomplete.Read(0x4f068d, 0x6, 0x0, 0x0, 0x0, 0x0)
	/media/sf_gopath/src/go-input-autocomplete/input_autocomplete.go:50 +0xd4
main.main()
	/media/sf_gopath/src/go-input-autocomplete/cmd/main.go:9 +0x3a
exit status 2
`

**Comment by HemantJoshi11** [comment]
I will fix it.
